account/urls.py
from django.urls import path
from . import views

app_name='account'

urlpatterns = [
    path('signup/',views.signup_user,name='signup'),
    path('login/',views.login_user,name='login'),
    path('logout/',views.logout_user,name='logout'),
]

articles/urls.py

from django.urls import path
from . import views
app_name='articles'
urlpatterns = [
    path('',views.articles,name='list'),
    path('<str:slug>/',views.articles_details,name='detail'),
    path('create_art',views.create_article,name='create_article')
]

blog/urls.py

from django.urls import include, path,re_path
from django.contrib import admin
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('account/',include('account.urls')),
    path('about/',views.about),
    path('',views.home)
]

urlpatterns+=staticfiles_urlpatterns()
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

account/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Article(models.Model):
    title=models.CharField(max_length=100)
    slug=models.SlugField()
    body=models.TextField()
    date=models.DateTimeField(auto_now_add=True)
    thumb=models.ImageField(default='default.jpg',blank=True)
    author= models.ForeignKey(User,on_delete=models.DO_NOTHING,default=None)
    def __str__(self):
        return self.title 

    def snippet(self):
        return self.body[:50]+'...'

 

articles/forms.py
from django import forms
from . import models

class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.Article
        fields=['title','body','slug','thumb']

account/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import login,logout


def signup_user(request):
    if request.user.is_authenticated:
            return redirect('articles:list')
    if request.method=="POST":
        form=UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request,user)
            return redirect('articles:list')
    else:
        form=UserCreationForm()
    return render(request,'account/signup.html',{'form':form})


def login_user(request):
    if request.user.is_authenticated:
            return redirect('articles:list')
    if request.method=="POST":
        form=AuthenticationForm(data=request.POST)
        if form.is_valid():
            user= form.get_user()
            login(request,user)
            return redirect('articles:list')
    else:
        form=AuthenticationForm()
    return render(request,'account/login.html',{'form':form})


def logout_user(request):
    if request.method == 'POST':
        logout(request)
    return redirect('/')

articles/views.py
from django.shortcuts import render,redirect
from .models import Article
from django.contrib.auth.decorators import login_required
from . import forms

@login_required(login_url='/')
def articles(request):
    articles=Article.objects.all().order_by('date')
    return render(request,'articles/articles.html',{'articles':articles})

@login_required(login_url='/')
def articles_details(request,slug):
    article = Article.objects.get(slug=slug)
    return render(request,'articles/article.html', { 'article': article })
    # return HttpResponse(slug)


@login_required(login_url='/account/login')
def create_article(request):
    if request.method=='POST':
        form=forms.CreateArticle(request.POST,request.FILES)
        if form.is_valid():
            instance=form.save(commit=False)
            instance.author=request.user
            instance.save()
            return redirect('articles:list')
    else:
        form = forms.CreateArticle()
    return render(request,'articles/create_article.html',{'form':form})


blog/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.shortcuts import render,redirect
def home(request):
    if request.user.is_authenticated:
            return redirect('articles:list')
    # return HttpResponse('Home page')
    return render(request,'home.html')

def about(request):
    # return HttpResponse('About page')
    return render(request,'about.html')

articles/templates/articles/article.html
<!DOCTYPE HTML>
{% load static %}
<html>
	<head>
		<title>URFU BLOG</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="{% static 'css/main.css' %}" />
	</head>
	<body class="single is-preload">

		<!-- Wrapper -->
			<div id="wrapper">

				<!-- Header -->
					<header id="header">
						<h1><a href="{% url 'articles:list' %}">URFU BLOG</a></h1>
						<nav class="links">
							<ul>
								<li><a href="{% url 'articles:create_article'%}">Create article</a></li>
                <li><a href="#"> </a></li>
                <li><a href="#"> </a></li>
                <li><a href="#"> </a></li>
                <li><a href="#"> </a></li>
							</ul>
						</nav>
						<nav class="main">
							<ul>
								<li class="search">
									<a class="fa-search" href="#search">Search</a>
									<form id="search" method="get" action="#">
										<input type="text" name="query" placeholder="Search" />
									</form>
								</li>
								<li class="menu">
									<a class="fa-bars" href="#menu">Menu</a>
								</li>
							</ul>
						</nav>
					</header>

				<!-- Menu -->
					<section id="menu">

						<!-- Search -->
							<section>
								<form class="search" method="get" action="#">
									<input type="text" name="query" placeholder="Search" />
								</form>
							</section>

						<!-- Links -->
							<section>
								<ul class="links">
									<li>
										<a href="#">
											<h3>Lorem ipsum</h3>
											<p>Feugiat tempus veroeros dolor</p>
										</a>
									</li>
									<li>
										<a href="#">
											<h3>Dolor sit amet</h3>
											<p>Sed vitae justo condimentum</p>
										</a>
									</li>
									<li>
										<a href="#">
											<h3>Feugiat veroeros</h3>
											<p>Phasellus sed ultricies mi congue</p>
										</a>
									</li>
									<li>
										<a href="#">
											<h3>Etiam sed consequat</h3>
											<p>Porta lectus amet ultricies</p>
										</a>
									</li>
								</ul>
							</section>

						<!-- Actions -->
							<section>
								<ul class="actions stacked">
									{% comment %} <li><a href="/account/login" class="button large fit">Log In</a></li> {% endcomment %}
									<li>	<form action="/account/logout/" method="post" class="form-example">
										{% csrf_token %}
										<input type="submit" class="button large fit" value="logout!" />
	
									</form /></li>
								</ul>
								
							</section>

					</section>

				<!-- Main -->
					<div id="main">

						<!-- Post -->
							<article class="post">
								<header>
									<div class="title">
										<h2><a href="#">{{article.title}}</a></h2>
										<p>Lorem ipsum dolor amet nullam consequat etiam feugiat</p>
									</div>
									<div class="meta">
										<time class="published" datetime="2015-11-01">{{article.date}}</time>
										<a href="#" class="author"><span class="name">{{article.author}}</span><img src="{% static "/images/avatar.jpg "%}" alt="" /></a>
									</div>
								</header>
								<span class="image featured"><img src="{{article.thumb.url}}" alt="" /></span>
								<p>{{article.body}}</p>
								<footer>
									<ul class="stats">
										<li><a href="#">General</a></li>
										<li><a href="#" class="icon solid fa-heart">28</a></li>
										<li><a href="#" class="icon solid fa-comment">128</a></li>
									</ul>
								</footer>
							</article>

					</div>

				<!-- Footer -->
					<section id="footer">
						<ul class="icons">
							<li><a href="#" class="icon brands fa-twitter"><span class="label">Twitter</span></a></li>
							<li><a href="#" class="icon brands fa-facebook-f"><span class="label">Facebook</span></a></li>
							<li><a href="#" class="icon brands fa-instagram"><span class="label">Instagram</span></a></li>
							<li><a href="#" class="icon solid fa-rss"><span class="label">RSS</span></a></li>
							<li><a href="#" class="icon solid fa-envelope"><span class="label">Email</span></a></li>
						</ul>
						<p class="copyright">&copy; Untitled. Design: <a href="#">URFU BLOG</a>. Images: <a href="http://unsplash.com">Unsplash</a>.</p>
					</section>

			</div>

	<!-- Scripts -->
<script src={% static   "js/jquery.min.js" %} ></script>
<script src={% static   "js/browser.min.js" %} ></script>
<script src={% static   "js/breakpoints.min.js" %} ></script>
<script src={% static   "js/util.js" %} ></script>
<script src={% static   "js/main.js" %} ></script>

	</body>
</html>

articles/templates/articles/articles.html
{% extends "base_layout.html" %} 
{% block content %}
{% load static %}
  
       <!-- Post -->
     {% for article in articles %}
     <article class="post">
      <header>
        <div class="title">
          <h2><a href="{% url 'articles:detail' slug=article.slug %}">{{article.title}}</a></h2>
          <p>Lorem ipsum dolor amet nullam consequat etiam feugiat</p>
        </div>
        <div class="meta">
          <time class="published" datetime="2015-11-01"
            >{{article.date}}</time
          >
          <a href="#" class="author"
            ><span class="name">{{article.author}}</span
            ><img src='{% static "/images/avatar.jpg "%}' alt=""
          /></a>
        </div>
      </header>
      <a href="{% url 'articles:detail' slug=article.slug %}" class="image featured"
        ><img src='{{article.thumb.url}}' alt=""/></a>
      <p>
        {{article.snippet}}
      </p>
      <footer>
        <ul class="actions">
          <li>
            <a href="{% url 'articles:detail' slug=article.slug %}" class="button large">Continue Reading</a>
          </li>
        </ul>
        <ul class="stats">
          <li><a href="#">General</a></li>
          <li><a href="#" class="icon solid fa-heart">28</a></li>
          <li><a href="#" class="icon solid fa-comment">128</a></li>
        </ul>
      </footer>
    </article>
    {% endfor %}
 
    
{% endblock content %}

articles/templates/articles/create_article.html
<!DOCTYPE html>
{% extends "base_layout.html" %} 
{% block content %}
{% load static %}
<section>
  <h1>Create Article</h1>
      
  <form action='{% url 'articles:create_article' %}' method='post' enctype='multipart/form-data'>
    {% csrf_token %}
    {% autoescape off %}{{ form }}{% endautoescape %} 

    <input type='submit' value='Create Article' />
  </form>

</section>
      
{% endblock content %}

templates/About.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>About</title>
</head>
<body>
    <h1>This is About Page</h1>
    <p>Welcome in About</p>
</body>
</html>

templates/base_layout.html


{% load static %}
<html>
  <head>
    <title>URFU BLOG</title>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, user-scalable=no"
    />
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
  </head>
  <body class="is-preload">
    <!-- Wrapper -->
    <div id="wrapper">

      <!-- Header -->
          <header id="header">
            <h1><a href="{% url 'articles:list' %}">URFU BLOG</a></h1>
            <nav class="links">
              <ul>
                <li><a href="{% url 'articles:create_article'%}">Create article</a></li>
                <li><a href="#"> </a></li>
                <li><a href="#"> </a></li>
                <li><a href="#"> </a></li>
                <li><a href="#"> </a></li>
              </ul>
            </nav>
            <nav class="main">
              <ul>
                <li class="search">
                  <a class="fa-search" href="#search">Search</a>
                  <form id="search" method="get" action="#">
                    <input type="text" name="query" placeholder="Search" />
                  </form>
                </li>
                <li class="menu">
                  <a class="fa-bars" href="#menu">Menu</a>
                </li>
              </ul>
            </nav>
          </header>
      
      
          <!-- Menu -->
            <section id="menu">
        
              <!-- Search -->
              <section>
                <form class="search" method="get" action="#">
                  <input type="text" name="query" placeholder="Search" />
                </form>
              </section>
      
              <!-- Links -->
              <section>
                <ul class="links">
                  <li>
                    <a href="#">
                      <h3>Lorem ipsum</h3>
                      <p>Feugiat tempus veroeros dolor</p>
                    </a>
                  </li>
                  <li>
                    <a href="#">
                      <h3>Dolor sit amet</h3>
                      <p>Sed vitae justo condimentum</p>
                    </a>
                  </li>
                  <li>
                    <a href="#">
                      <h3>Feugiat veroeros</h3>
                      <p>Phasellus sed ultricies mi congue</p>
                    </a>
                  </li>
                  <li>
                    <a href="#">
                      <h3>Etiam sed consequat</h3>
                      <p>Porta lectus amet ultricies</p>
                    </a>
                  </li>
                </ul>
              </section>
      
              <!-- Actions -->
              <section>
                <ul class="actions stacked">
                  {% comment %} <li><a href="/account/login" class="button large fit">Log In</a></li> {% endcomment %}
                  <li>	<form action="/account/logout/" method="post" class="form-example">
										{% csrf_token %}
										<input type="submit" class="button large fit" value="logout!" />
	
									</form /></li>
                </ul>
              </section>
            </section>
    
    


      

      <!-- Main -->
        <div id="main">
          {% block content%}
          {% endblock %}
          <!-- Pagination -->
          <ul class="actions pagination">
            <li>
              <a href="" class="disabled button large previous">Previous Page</a>
            </li>
            <li><a href="#" class="button large next">Next Page</a></li>
          </ul>
        </div>

      <!-- Sidebar --> 
        <section id="sidebar">
          <!-- Intro -->
          <section id="intro">
            <a href="#" class="logo"
              ><img src={% static "images/logo.jpg" %} alt="" /></a
            >
            <header>
              <h2>URFU BLOG</h2>
              <p>
                Another fine responsive site template by
                <a href="http://html5up.net">HTML5 UP</a>
              </p>
            </header>
          </section>

          <!-- Mini Posts -->
          <section>
            <div class="mini-posts">
              <!-- Mini Post -->
              <article class="mini-post">
                <header>
                  <h3><a href="#">Vitae sed condimentum</a></h3>
                  <time class="published" datetime="2015-10-20"
                    >October 20, 2015</time
                  >
                  <a href="#" class="author"
                    ><img src={% static "images/avatar.jpg" %} alt="" /></a
                  >
                </header>
                <a href="#" class="image"
                  ><img src={% static "images/pic04.jpg" %} alt=""
                /></a>
              </article>
            </div>
          </section>

          <!-- Posts List -->
          <section>
            <ul class="posts">
              <li>
                <article>
                  <header>
                    <h3>
                      <a href="#"
                        >Lorem ipsum fermentum ut nisl vitae</a
                      >
                    </h3>
                    <time class="published" datetime="2015-10-20"
                      >October 20, 2015</time
                    >
                  </header>
                  <a href="#" class="image"
                    ><img src={% static "images/pic08.jpg" %} alt=""
                  /></a>
                </article>
              </li>
          
            </ul>
            </section>
  
        <!-- About -->
          <section class="blurb">
            <h2>About</h2>
            <p>
              Mauris neque quam, fermentum ut nisl vitae, convallis maximus nisl.
              Sed mattis nunc id lorem euismod amet placerat. Vivamus porttitor
              magna enim, ac accumsan tortor cursus at phasellus sed ultricies.
            </p>
            <ul class="actions">
              <li><a href="#" class="button">Learn More</a></li>
            </ul>
          </section>


  
   
      <section id="footer">
      <ul class="icons">
        <li>
          <a href="#" class="icon brands fa-twitter"
            ><span class="label">Twitter</span></a
          >
        </li>
        <li>
          <a href="#" class="icon brands fa-facebook-f"
            ><span class="label">Facebook</span></a
          >
        </li>
        <li>
          <a href="#" class="icon brands fa-instagram"
            ><span class="label">Instagram</span></a
          >
        </li>
        <li>
          <a href="#" class="icon solid fa-rss"
            ><span class="label">RSS</span></a
          >
        </li>
        <li>
          <a href="#" class="icon solid fa-envelope"
            ><span class="label">Email</span></a
          >
        </li>
      </ul>
      <p class="copyright">
        &copy; Untitled. Design: <a href="#">URFU BLOG</a>.
        Images: <a href="http://unsplash.com">Unsplash</a>.
      </p>
    
    </section>

       
 
  
  
  
  </section>

</div>

<!-- Scripts -->
<script src={% static   "js/jquery.min.js" %} ></script>
<script src={% static   "js/browser.min.js" %} ></script>
<script src={% static   "js/breakpoints.min.js" %} ></script>
<script src={% static   "js/util.js" %} ></script>
<script src={% static   "js/main.js" %} ></script>
</body>
</html>

templates/home.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title></title>
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
    <link rel="stylesheet" href="{% static 'css/home.css' %}" />


  </head>
  <body>
   
    <section class='center'>
    <h1 class'home-title'>URFU BLOG</h1>

    {% block content%}
    {% endblock %}
    <div>
    <a href='{% url 'account:login' %}'>Login</a>
    <span>or</span>
    <a href='{% url 'account:signup' %}'>Signup</a>
    </div>
</section>
    <script src="" async defer></script>
  </body>
</html>